package config

import (
	"os"
	"path/filepath"
	"testing"
)

func TestSecretsAutoGeneratedOnceAndPersisted(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "secrets.env")
	t.Setenv("DATABASE_URL", "postgres://x@localhost/db")
	t.Setenv("AUTH_SECRET", "")
	t.Setenv("ENCRYPTION_KEY", "")
	t.Setenv("DBVAULT_SECRETS_FILE", path)
	t.Setenv("AUTO_GENERATE_SECRETS", "true")

	c1, err := Load()
	if err != nil {
		t.Fatal(err)
	}
	fi, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if fi.Mode().Perm() != 0o600 {
		t.Fatalf("secrets file mode %v, want 0600", fi.Mode().Perm())
	}
	c2, err := Load()
	if err != nil {
		t.Fatal(err)
	}
	if string(c1.EncryptionKey) != string(c2.EncryptionKey) || string(c1.AuthSecret) != string(c2.AuthSecret) {
		t.Fatal("secrets must be stable across restarts")
	}
	if len(c1.EncryptionKey) != 32 {
		t.Fatal("encryption key must be 32 bytes")
	}
}

func TestRejectsMissingOrWeakSecrets(t *testing.T) {
	t.Setenv("DATABASE_URL", "postgres://x@localhost/db")
	t.Setenv("DBVAULT_SECRETS_FILE", "")
	t.Setenv("AUTH_SECRET", "short")
	t.Setenv("ENCRYPTION_KEY", "AAAA")
	if _, err := Load(); err == nil {
		t.Fatal("weak secrets must be rejected")
	}
	t.Setenv("AUTH_SECRET", "0123456789abcdef0123456789abcdef")
	if _, err := Load(); err == nil {
		t.Fatal("short encryption key must be rejected")
	}
	t.Setenv("ENCRYPTION_KEY", "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=")
	if _, err := Load(); err != nil {
		t.Fatalf("valid config rejected: %v", err)
	}
}

func TestVerifyModeValidation(t *testing.T) {
	t.Setenv("DATABASE_URL", "postgres://x@localhost/db")
	t.Setenv("AUTH_SECRET", "0123456789abcdef0123456789abcdef")
	t.Setenv("ENCRYPTION_KEY", "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=")
	t.Setenv("VERIFY_MODE", "server")
	t.Setenv("VERIFY_POSTGRES_URL", "")
	if _, err := Load(); err == nil {
		t.Fatal("server mode without VERIFY_POSTGRES_URL must fail")
	}
	t.Setenv("VERIFY_MODE", "kubernetes")
	if _, err := Load(); err == nil {
		t.Fatal("unknown verify mode must fail")
	}
}
